"""viva-marketplace — the ecosystem ledger for the vivarium / process-bigraph workbench.

Two data files ship with this package:

- ``modules.json`` — the registry of ecosystem repos (name, source, description,
  tags). The single source of truth for "what repos exist" in the ecosystem.
  Previously lived in ``viva_superpowers/catalog/modules.json``; moved here so
  the ledger is owned by a dedicated repo rather than the Claude-Code plugin.
- ``ecosystem-index.json`` — an aggregated artifact index: every repo's
  processes / steps / composites / studies / investigations (name + description
  + counts), so a workbench can browse the whole ecosystem WITHOUT installing
  each repo. Built by cloning + scanning each repo's source — no published
  dashboard required (``scripts/build_ecosystem_index.py``); regenerated by CI.

Consumers (viva-superpowers, vivarium-workbench) read these via ``load_modules()``
/ ``load_ecosystem_index()`` so the on-disk location is an implementation detail.
"""
from __future__ import annotations

import json
from importlib import resources
from typing import Any

__all__ = ["load_modules", "load_ecosystem_index", "MODULES_FILE", "INDEX_FILE"]

MODULES_FILE = "modules.json"
INDEX_FILE = "ecosystem-index.json"


def _load(name: str, default: Any) -> Any:
    try:
        with resources.files(__name__).joinpath(name).open("r", encoding="utf-8") as fh:
            return json.load(fh)
    except (FileNotFoundError, ModuleNotFoundError, OSError, json.JSONDecodeError):
        return default


def load_modules() -> list[dict]:
    """Return the ecosystem repo registry as a list of module dicts."""
    data = _load(MODULES_FILE, [])
    if isinstance(data, dict):
        data = data.get("modules") or []
    return [m for m in data if isinstance(m, dict)]


def load_ecosystem_index() -> dict:
    """Return the aggregated artifact index. Shape:

        {"generated_at": <iso|null>,
         "repos": [{"name", "source", "description", "published",
                    "processes": [{"name","description"}], "steps": [...],
                    "composites": [...], "studies": [...], "investigations": [...],
                    "counts": {"processes","steps","composites","studies","investigations"}}]}

    Returns ``{"repos": []}`` when the index hasn't been generated yet.
    """
    data = _load(INDEX_FILE, {"repos": []})
    if not isinstance(data, dict):
        return {"repos": []}
    data.setdefault("repos", [])
    return data
