"""viva-marketplace — the ecosystem ledger for the vivarium / process-bigraph workbench.

Data files shipped with this package:

- ``modules.json`` — the registry of ecosystem repos (name, source, description,
  tags). The single source of truth for "what repos exist" in the ecosystem.
  Previously lived in ``viva_superpowers/catalog/modules.json``; moved here so
  the ledger is owned by a dedicated repo rather than the Claude-Code plugin.
- ``ecosystem-index.json`` — an aggregated artifact index: every repo's
  processes / steps / composites / studies / investigations (name + description
  + counts), plus a per-repo reproducibility/FAIR-style ``attestation`` score.
  Built by cloning + scanning each repo's source — no published dashboard
  required (``scripts/build_ecosystem_index.py``); regenerated by CI.
- ``composability-graph.json`` — EXPERIMENTAL: a best-effort cross-repo port
  compatibility graph (see ``viva_marketplace.composability``). Not a verified
  wiring guarantee.
- ``schemas/*.schema.json`` — JSON Schema (draft 2020-12) for the three files
  above.

Consumers (viva-superpowers, vivarium-workbench) read these via ``load_modules()``
/ ``load_ecosystem_index()`` / ``load_composability_graph()`` so the on-disk
location is an implementation detail.
"""
from __future__ import annotations

import json
from importlib import metadata, resources
from typing import Any

__all__ = [
    "COMPOSABILITY_FILE",
    "INDEX_FILE",
    "MODULES_FILE",
    "__version__",
    "load_composability_graph",
    "load_ecosystem_index",
    "load_modules",
    "load_schema",
]

try:
    __version__ = metadata.version("viva-marketplace")
except metadata.PackageNotFoundError:  # pragma: no cover — not installed, e.g. ad hoc script use
    __version__ = "0.0.0+unknown"

MODULES_FILE = "modules.json"
INDEX_FILE = "ecosystem-index.json"
COMPOSABILITY_FILE = "composability-graph.json"


def _load(name: str, default: Any) -> Any:
    try:
        with resources.files(__name__).joinpath(name).open("r", encoding="utf-8") as fh:
            return json.load(fh)
    except (FileNotFoundError, ModuleNotFoundError, OSError, json.JSONDecodeError):
        return default


def load_modules() -> list[dict]:
    """Return the ecosystem repo registry as a list of module dicts."""
    data = _load(MODULES_FILE, [])
    if isinstance(data, dict):
        data = data.get("modules") or []
    return [m for m in data if isinstance(m, dict)]


def load_ecosystem_index() -> dict:
    """Return the aggregated artifact index. Shape:

        {"schema_version": <int>, "generated_at": <iso|null>,
         "repos": [{"name", "source", "description", "cloned",
                    "processes": [{"name","description"}], "steps": [...],
                    "composites": [...], "studies": [...], "investigations": [...],
                    "counts": {"processes","steps","composites","studies","investigations"},
                    "attestation": {"score", "pinned_ref", ...}}]}

    Returns ``{"repos": []}`` when the index hasn't been generated yet.
    """
    data = _load(INDEX_FILE, {"repos": []})
    if not isinstance(data, dict):
        return {"repos": []}
    data.setdefault("repos", [])
    return data


def load_composability_graph() -> dict:
    """Return the EXPERIMENTAL cross-repo port-compatibility graph (see
    ``viva_marketplace.composability``). Returns an empty graph shape when it
    hasn't been generated yet."""
    data = _load(COMPOSABILITY_FILE, {"edges": []})
    if not isinstance(data, dict):
        return {"edges": []}
    data.setdefault("edges", [])
    return data


def load_schema(name: str) -> dict:
    """Load one of the packaged JSON Schemas by filename, e.g.
    ``load_schema("modules.schema.json")``."""
    with resources.files(__name__).joinpath("schemas").joinpath(name).open("r", encoding="utf-8") as fh:
        return json.load(fh)
